# SPDX-License-Identifier: Apache-2.0
#
# Houdini  A container escape artist
# Copyright (c) 2022  William Findlay
#
# February 25, 2022  William Findlay  Created this.
#

FROM houdini:latest as houdini

FROM ubuntu:21.10
COPY --from=houdini houdini /usr/local/bin/houdini

CMD ["sleep", "infinity"]

# vi:ft=dockerfile #
